aws_error_utils/__init__.py,sha256=73sOoasHyZYcjIVNJC_OvWIEd6eAXoF0AQNdFJ8io24,846
aws_error_utils/aws_error_utils.py,sha256=k3hTbqM-P7xY3Lg_aA1AVHeEoVwkAJyVXwwNbCSvtZ0,8331
aws_error_utils/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
aws_error_utils-2.7.0.dist-info/LICENSE,sha256=9j8RqO8bPFqn4auDoWpegssMFBSlrw52EoRAO4PJyOA,11340
aws_error_utils-2.7.0.dist-info/WHEEL,sha256=vxFmldFsRN_Hx10GDvsdv1wroKq8r5Lzvjp6GZ4OO8c,88
aws_error_utils-2.7.0.dist-info/METADATA,sha256=Cig4jwvwpp466AFkR4A5cTkoZ2iEjWEq5IzPe0Ey6QE,9568
aws_error_utils-2.7.0.dist-info/RECORD,,
